### ISSUE TITLE
Deploy it on heroku

### ISSUE THREAD

**Issue by CodeDotJS** [darkfist/headlines#1]
Deploy `headlines` to [`heroku`](https://www.heroku.com) for previews and quick testing.

**Comment by darkfist** [comment]
Ok I will do that. 

Actually I already hosted this at darkfist.pythonanywhere.com , but don't don't know why the news headlines are not showing up there. Only weather and currency conversion is displayed there. 

It's working fine when I run it on localhost,  don't know what's the problem with PythonAnywhere :/
I will try to deploy it on Heroku and see :)

**Comment by CodeDotJS** [comment]
Sure!
Update the readme when you are done.
